[versions]
kotlin = "1.7.0"
android-gradle = "7.4.0-alpha09"
compose-ui = "1.2.1"
compose-compiler = "1.2.0"
orbitmvi = "4.3.2"
androidx-room = "2.4.2"
coroutines = "1.6.4"
ksp = "1.7.0-1.0.6"
anvil = "2.4.1"
dagger = "2.43.2"
tangle = "0.15.0"
lifecycle = "2.5.1"
ktlint = "0.46.1"
kotlinter = "3.11.1"
kotlinPoet = "1.12.0"
androidCacheFix = "2.5.6"

test-kotlinCompileTesting = "1.4.9"

[libraries]
kotlin-android-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
android-plugin = { module = "com.android.tools.build:gradle", version.ref = "android-gradle" }
desugaring = { module = "com.android.tools:desugar_jdk_libs", version = "1.2.0" }

coroutines-lib = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

ksp-plugin = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
anvil-plugin = { module = "com.squareup.anvil:gradle-plugin" , version.ref = "anvil" }
anvil-compiler-api = { module = "com.squareup.anvil:compiler-api", version.ref = "anvil"}
anvil-compiler-utils = { module = "com.squareup.anvil:compiler-utils", version.ref = "anvil"}

dagger-core = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }

compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose-ui" }
compose-uitooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" , version.ref = "compose-ui" }
compose-uitooling-core = { module = "androidx.compose.ui:ui-tooling" , version.ref = "compose-ui" }
compose-material = { module = "androidx.compose.material:material" , version.ref = "compose-ui" }
compose-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" , version.ref = "compose-ui" }
compose-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" , version.ref = "compose-ui" }

tangle-plugin = { module = "com.rickbusarow.tangle:tangle-gradle-plugin", version.ref = "tangle" }
tangle-viewmodel-api = { module = "com.rickbusarow.tangle:tangle-viewmodel-api", version.ref = "tangle" }

junit4 = { module = "junit:junit", version = "4.13.2" }

fragNav = { module = "com.github.ncapdevi:FragNav", version = "3.3.0" }
timber = { module = "com.jakewharton.timber:timber", version = "5.0.1" }

androidx-test-junit4 = { module = "androidx.test.ext:junit", version = "1.1.3" }
androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version = "3.4.0" }

androidx-activity-compose = { module = "androidx.activity:activity-compose", version = "1.5.1" }
androidx-core = { module = "androidx.core:core-ktx", version = "1.8.0" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.5.0" }
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version = "1.5.2" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }

androidx-coordinatorlayour = { module = "androidx.coordinatorlayout:coordinatorlayout", version = "1.2.0" }

material = { module = "com.google.android.material:material", version = "1.6.1" }

orbitmvi-viewmodel = { module = "org.orbit-mvi:orbit-viewmodel", version.ref = "orbitmvi" }
orbitmvi-compose = { module = "org.orbit-mvi:orbit-compose", version.ref = "orbitmvi" }

kotlinter-plugin = { module = "org.jmailen.gradle:kotlinter-gradle", version.ref = "kotlinter" }

autoService-Ksp = { module = "dev.zacsweers.autoservice:auto-service-ksp", version = "1.0.0" }
autoService-annotations = { module = "com.google.auto.service:auto-service-annotations", version = "1.0.1" }

kotlinPoet-base = { module = "com.squareup:kotlinpoet", version.ref = "kotlinPoet" }
kotlinPoet-ksp = { module = "com.squareup:kotlinpoet-ksp", version.ref = "kotlinPoet" }

androidCacheFix = { module = "org.gradle.android.cache-fix:org.gradle.android.cache-fix.gradle.plugin", version.ref = "androidCacheFix" }

test-kotlinCompile-base = { module = "com.github.tschuchortdev:kotlin-compile-testing", version.ref = "test-kotlinCompileTesting" }
test-kotlinCompile-ksp = { module = "com.github.tschuchortdev:kotlin-compile-testing-ksp", version.ref = "test-kotlinCompileTesting" }

[plugins]
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "android-gradle" }
android-library = { id = "com.android.library", version.ref = "android-gradle" }

anvil = { id = "com.squareup.anvil", version.ref = "anvil" }

ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
benManesVersions = { id = "com.github.ben-manes.versions", version = "0.42.0" }
gradleDoctor = { id = "com.osacky.doctor", version = "0.8.1" }

tangle = { id = "com.rickbusarow.tangle", version.ref = "tangle" }

kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }

[bundles]
compose-ui-core = ["compose-ui", "compose-uitooling-preview", "compose-material"]
compose-ui-debug = ["compose-uitooling-core", "compose-test-manifest"]
compose-test = ["compose-test-junit4"]

androidx-core = ["androidx-core", "androidx-appcompat", "androidx-fragment"]
androidx-test = ["androidx-test-junit4", "androidx-test-espresso-core"]

orbitmvi = ["orbitmvi-viewmodel", "orbitmvi-compose"]

kotlinPoet = ["kotlinPoet-base", "kotlinPoet-ksp"]
test-kotlinCompile = ["test-kotlinCompile-base", "test-kotlinCompile-ksp"]

anvil-compiler = ["anvil-compiler-api", "anvil-compiler-utils"]
