name: Android CI

on:
    push:
        branches:
            - develop
            - main
    pull_request:
        types: [ opened, synchronize, reopened ]
jobs:
    validate:
        runs-on: ubuntu-latest

        steps:
            -   name: Cancel Workflow Action
                uses: styfle/cancel-workflow-action@0.10.0

            -   name: Checkout
                uses: actions/checkout@v3
                with:
                    token: ${{ secrets.ANDROID_CI_GITHUB_TOKEN }}
                    repository: ${{ github.event.pull_request.head.repo.full_name }}
                    ref: ${{ github.event.pull_request.head.ref }}

            -   name: Set up JDK 11
                uses: actions/setup-java@v3
                with:
                    distribution: 'temurin'
                    java-version: 11

            -   name: Setup Android SDK
                uses: android-actions/setup-android@v2

            -   name: Configure Android SDK
                run: sdkmanager "build-tools;33.0.0" "platforms;android-33"

            -   name: Validating Gradle wrapper checksum
                uses: gradle/wrapper-validation-action@v1

            -   run: chmod +x ./gradlew

            -   name: Format code
                uses: gradle/gradle-build-action@v2
                with:
                    arguments: formatKotlin

            -   id: commit_formatted_code
                name: Commit formatted code
                uses: EndBug/add-and-commit@v9
                with:
                    message: Format code
                    default_author: github_actions
                    add: "*.kt"

            -   name: Cancelling due to formatted code
                uses: andymckay/cancel-action@0.2
                if: steps.commit_formatted_code.outputs.pushed == 'true'

            -   name: Run validations
                uses: gradle/gradle-build-action@v2
                id: gradle
                with:
                    arguments: lintKotlin :app:assembleDebug :app:lintDebug --stacktrace # run tests here
                if: steps.commit_formatted_code.outputs.pushed == 'false'
