name: Android CI

on:
    push:
        branches:
            - develop
            - main
    pull_request:
        types: [ opened, synchronize, reopened ]
jobs:
    validate:
        runs-on: ubuntu-latest

        steps:
            -   name: Cancel Workflow Action
                uses: styfle/cancel-workflow-action@0.11.0

            -   name: Checkout
                uses: actions/checkout@v3
                with:
                    token: ${{ secrets.ANDROID_CI_GITHUB_TOKEN }}
                    repository: ${{ github.event.pull_request.head.repo.full_name }}
                    ref: ${{ github.event.pull_request.head.ref }}

            -   name: Set up JDK 11
                uses: actions/setup-java@v3
                with:
                    distribution: 'temurin'
                    java-version: 11

            -   name: Setup Android SDK
                uses: android-actions/setup-android@v2

            -   name: Configure Android SDK
                run: sdkmanager "build-tools;33.0.0" "platforms;android-33"

            -   name: Validating Gradle wrapper checksum
                uses: gradle/wrapper-validation-action@v1

            -   name: Format code
                uses: gradle/gradle-build-action@v2
                with:
                    arguments: formatKotlin

            -   id: commit_formatted_code
                name: Commit formatted code
                uses: EndBug/add-and-commit@v9
                with:
                    message: Format code
                    default_author: github_actions
                    add: "*.kt"

            -   name: Cancelling due to formatted code
                uses: andymckay/cancel-action@0.3
                if: steps.commit_formatted_code.outputs.pushed == 'true'

            -   name: Run validations
                uses: gradle/gradle-build-action@v2
                id: gradle
                with:
                    arguments: lintKotlin lintDebug :app:assembleDebug --stacktrace # run tests here
                if: steps.commit_formatted_code.outputs.pushed == 'false'

            -   uses: github/codeql-action/upload-sarif@v2
                if: steps.commit_formatted_code.outputs.pushed == 'false' && success() || failure()
                with:
                    sarif_file: app/build/reports/lint-results-debug.sarif
                    category: lint

    actionlint:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   uses: reviewdog/action-actionlint@v1

    detekt:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   name: Detekt
                uses: alaegin/Detekt-Action@v1.22.0-RC2
                with:
                    github_token: ${{ secrets.github_token }}
                    detekt_config: ./config/detekt/detekt.yml
                    reviewdog_filter: file # always analyse whole file that was added/modified

    modulecheck:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   name: Set up JDK 11
                uses: actions/setup-java@v3
                with:
                    distribution: 'temurin'
                    java-version: 11
            -   name: Validating Gradle wrapper checksum
                uses: gradle/wrapper-validation-action@v1

            -   name: Check modules
                uses: gradle/gradle-build-action@v2
                with:
                    arguments: moduleCheck --no-daemon
